os: osx
osx_image: xcode9.3beta
language: node_js
node_js: stable

before_install:

install:
  - npm install

script:
  - npm run w-build
  - npm run mac-app
  - npm run mac-dmg

branches:
  only:
    - master

before_deploy:
  - git config --local user.name "zsirfs"
  - git config --local user.email "zhenglfsir@gmail.com"
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  provider: releases
  api_key: 
    secure: $GITHUB_TOKEN
  file_blob: true
  overwrite: true
  file: release/**/*
  skip_cleanup: true
  on:
    repo: zsirfs/hexo-helper
    tags: true
    all_branches: true
