os: osx
osx_image: xcode9.3beta
language: node_js
node_js: stable

before_install:

install:
  - npm install

script:
  - npm run w-build
  - npm run mac-app
  - npm run mac-dmg

notifications:
  email: false

branches:
    only:
    - master
    - /v\d+\.\d+[a-z]/

before_deploy:

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_blob: true
  overwrite: true
  file: release/*
  skip_cleanup: true
  on:
    repo: zsirfs/hexo-helper
    tags: false
    all_branches: true
